/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.CreateWorkflowTransitionRule;
import org.openapitools.client.model.CreateWorkflowTransitionRulesDetailsConditions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateWorkflowTransitionDetailsRules
 */
public class CreateWorkflowTransitionDetailsRulesTest {
    private final CreateWorkflowTransitionDetailsRules model = new CreateWorkflowTransitionDetailsRules();

    /**
     * Model tests for CreateWorkflowTransitionDetailsRules
     */
    @Test
    public void testCreateWorkflowTransitionDetailsRules() {
        // TODO: test CreateWorkflowTransitionDetailsRules
    }

    /**
     * Test the property 'conditions'
     */
    @Test
    public void conditionsTest() {
        // TODO: test conditions
    }

    /**
     * Test the property 'validators'
     */
    @Test
    public void validatorsTest() {
        // TODO: test validators
    }

    /**
     * Test the property 'postFunctions'
     */
    @Test
    public void postFunctionsTest() {
        // TODO: test postFunctions
    }

}
