/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DashboardGadgetUpdateRequestPosition
 */
public class DashboardGadgetUpdateRequestPositionTest {
    private final DashboardGadgetUpdateRequestPosition model = new DashboardGadgetUpdateRequestPosition();

    /**
     * Model tests for DashboardGadgetUpdateRequestPosition
     */
    @Test
    public void testDashboardGadgetUpdateRequestPosition() {
        // TODO: test DashboardGadgetUpdateRequestPosition
    }

    /**
     * Test the property 'theRowPositionOfTheGadget'
     */
    @Test
    public void theRowPositionOfTheGadgetTest() {
        // TODO: test theRowPositionOfTheGadget
    }

    /**
     * Test the property 'theColumnPositionOfTheGadget'
     */
    @Test
    public void theColumnPositionOfTheGadgetTest() {
        // TODO: test theColumnPositionOfTheGadget
    }

}
