/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.LinkedHashSet;
import java.util.Set;
import org.openapitools.client.model.IssueFieldOptionScopeBeanGlobal;
import org.openapitools.client.model.ProjectScopeBean;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for IssueFieldOptionConfigurationScope
 */
public class IssueFieldOptionConfigurationScopeTest {
    private final IssueFieldOptionConfigurationScope model = new IssueFieldOptionConfigurationScope();

    /**
     * Model tests for IssueFieldOptionConfigurationScope
     */
    @Test
    public void testIssueFieldOptionConfigurationScope() {
        // TODO: test IssueFieldOptionConfigurationScope
    }

    /**
     * Test the property 'projects'
     */
    @Test
    public void projectsTest() {
        // TODO: test projects
    }

    /**
     * Test the property 'projects2'
     */
    @Test
    public void projects2Test() {
        // TODO: test projects2
    }

    /**
     * Test the property 'global'
     */
    @Test
    public void globalTest() {
        // TODO: test global
    }

}
