/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.coscene.jira.client.v3.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for ChangedValueBean
 */
public class ChangedValueBeanTest {
    private final ChangedValueBean model = new ChangedValueBean();

    /**
     * Model tests for ChangedValueBean
     */
    @Test
    public void testChangedValueBean() {
        // TODO: test ChangedValueBean
    }

    /**
     * Test the property 'fieldName'
     */
    @Test
    public void fieldNameTest() {
        // TODO: test fieldName
    }

    /**
     * Test the property 'changedFrom'
     */
    @Test
    public void changedFromTest() {
        // TODO: test changedFrom
    }

    /**
     * Test the property 'changedTo'
     */
    @Test
    public void changedToTest() {
        // TODO: test changedTo
    }

}
