/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.coscene.jira.client.v3.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for CustomFieldContextDefaultValueForgeObjectField
 */
public class CustomFieldContextDefaultValueForgeObjectFieldTest {
    private final CustomFieldContextDefaultValueForgeObjectField model = new CustomFieldContextDefaultValueForgeObjectField();

    /**
     * Model tests for CustomFieldContextDefaultValueForgeObjectField
     */
    @Test
    public void testCustomFieldContextDefaultValueForgeObjectField() {
        // TODO: test CustomFieldContextDefaultValueForgeObjectField
    }

    /**
     * Test the property '_object'
     */
    @Test
    public void _objectTest() {
        // TODO: test _object
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
