/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.coscene.jira.client.v3.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for EventNotificationField
 */
public class EventNotificationFieldTest {
    private final EventNotificationField model = new EventNotificationField();

    /**
     * Model tests for EventNotificationField
     */
    @Test
    public void testEventNotificationField() {
        // TODO: test EventNotificationField
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'key'
     */
    @Test
    public void keyTest() {
        // TODO: test key
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'custom'
     */
    @Test
    public void customTest() {
        // TODO: test custom
    }

    /**
     * Test the property 'orderable'
     */
    @Test
    public void orderableTest() {
        // TODO: test orderable
    }

    /**
     * Test the property 'navigable'
     */
    @Test
    public void navigableTest() {
        // TODO: test navigable
    }

    /**
     * Test the property 'searchable'
     */
    @Test
    public void searchableTest() {
        // TODO: test searchable
    }

    /**
     * Test the property 'clauseNames'
     */
    @Test
    public void clauseNamesTest() {
        // TODO: test clauseNames
    }

    /**
     * Test the property 'scope'
     */
    @Test
    public void scopeTest() {
        // TODO: test scope
    }

    /**
     * Test the property 'schema'
     */
    @Test
    public void schemaTest() {
        // TODO: test schema
    }

}
