/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.coscene.jira.client.v3.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for SecuritySchemes
 */
public class SecuritySchemesTest {
    private final SecuritySchemes model = new SecuritySchemes();

    /**
     * Model tests for SecuritySchemes
     */
    @Test
    public void testSecuritySchemes() {
        // TODO: test SecuritySchemes
    }

    /**
     * Test the property 'issueSecuritySchemes'
     */
    @Test
    public void issueSecuritySchemesTest() {
        // TODO: test issueSecuritySchemes
    }

}
