/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.coscene.jira.client.v3.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for SharePermissionInputBean
 */
public class SharePermissionInputBeanTest {
    private final SharePermissionInputBean model = new SharePermissionInputBean();

    /**
     * Model tests for SharePermissionInputBean
     */
    @Test
    public void testSharePermissionInputBean() {
        // TODO: test SharePermissionInputBean
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'projectId'
     */
    @Test
    public void projectIdTest() {
        // TODO: test projectId
    }

    /**
     * Test the property 'groupname'
     */
    @Test
    public void groupnameTest() {
        // TODO: test groupname
    }

    /**
     * Test the property 'projectRoleId'
     */
    @Test
    public void projectRoleIdTest() {
        // TODO: test projectRoleId
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    public void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'rights'
     */
    @Test
    public void rightsTest() {
        // TODO: test rights
    }

    /**
     * Test the property 'groupId'
     */
    @Test
    public void groupIdTest() {
        // TODO: test groupId
    }

}
