/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.coscene.jira.client.v3.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for WorkflowTransitionRules
 */
public class WorkflowTransitionRulesTest {
    private final WorkflowTransitionRules model = new WorkflowTransitionRules();

    /**
     * Model tests for WorkflowTransitionRules
     */
    @Test
    public void testWorkflowTransitionRules() {
        // TODO: test WorkflowTransitionRules
    }

    /**
     * Test the property 'workflowId'
     */
    @Test
    public void workflowIdTest() {
        // TODO: test workflowId
    }

    /**
     * Test the property 'postFunctions'
     */
    @Test
    public void postFunctionsTest() {
        // TODO: test postFunctions
    }

    /**
     * Test the property 'conditions'
     */
    @Test
    public void conditionsTest() {
        // TODO: test conditions
    }

    /**
     * Test the property 'validators'
     */
    @Test
    public void validatorsTest() {
        // TODO: test validators
    }

}
