/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.coscene.jira.client.v2.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for CreatedIssueTransition
 */
public class CreatedIssueTransitionTest {
    private final CreatedIssueTransition model = new CreatedIssueTransition();

    /**
     * Model tests for CreatedIssueTransition
     */
    @Test
    public void testCreatedIssueTransition() {
        // TODO: test CreatedIssueTransition
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'errorCollection'
     */
    @Test
    public void errorCollectionTest() {
        // TODO: test errorCollection
    }

}
