/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.coscene.jira.client.v2.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for CustomFieldContextDefaultValueMultiUserPicker
 */
public class CustomFieldContextDefaultValueMultiUserPickerTest {
    private final CustomFieldContextDefaultValueMultiUserPicker model = new CustomFieldContextDefaultValueMultiUserPicker();

    /**
     * Model tests for CustomFieldContextDefaultValueMultiUserPicker
     */
    @Test
    public void testCustomFieldContextDefaultValueMultiUserPicker() {
        // TODO: test CustomFieldContextDefaultValueMultiUserPicker
    }

    /**
     * Test the property 'contextId'
     */
    @Test
    public void contextIdTest() {
        // TODO: test contextId
    }

    /**
     * Test the property 'accountIds'
     */
    @Test
    public void accountIdsTest() {
        // TODO: test accountIds
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
