/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.coscene.jira.client.v2.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for CustomFieldValueUpdate
 */
public class CustomFieldValueUpdateTest {
    private final CustomFieldValueUpdate model = new CustomFieldValueUpdate();

    /**
     * Model tests for CustomFieldValueUpdate
     */
    @Test
    public void testCustomFieldValueUpdate() {
        // TODO: test CustomFieldValueUpdate
    }

    /**
     * Test the property 'issueIds'
     */
    @Test
    public void issueIdsTest() {
        // TODO: test issueIds
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

}
