/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.coscene.jira.client.v2.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for DashboardGadgetPosition
 */
public class DashboardGadgetPositionTest {
    private final DashboardGadgetPosition model = new DashboardGadgetPosition();

    /**
     * Model tests for DashboardGadgetPosition
     */
    @Test
    public void testDashboardGadgetPosition() {
        // TODO: test DashboardGadgetPosition
    }

    /**
     * Test the property 'theRowPositionOfTheGadget'
     */
    @Test
    public void theRowPositionOfTheGadgetTest() {
        // TODO: test theRowPositionOfTheGadget
    }

    /**
     * Test the property 'theColumnPositionOfTheGadget'
     */
    @Test
    public void theColumnPositionOfTheGadgetTest() {
        // TODO: test theColumnPositionOfTheGadget
    }

}
