/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.coscene.jira.client.v2.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for FieldConfigurationIssueTypeItem
 */
public class FieldConfigurationIssueTypeItemTest {
    private final FieldConfigurationIssueTypeItem model = new FieldConfigurationIssueTypeItem();

    /**
     * Model tests for FieldConfigurationIssueTypeItem
     */
    @Test
    public void testFieldConfigurationIssueTypeItem() {
        // TODO: test FieldConfigurationIssueTypeItem
    }

    /**
     * Test the property 'fieldConfigurationSchemeId'
     */
    @Test
    public void fieldConfigurationSchemeIdTest() {
        // TODO: test fieldConfigurationSchemeId
    }

    /**
     * Test the property 'issueTypeId'
     */
    @Test
    public void issueTypeIdTest() {
        // TODO: test issueTypeId
    }

    /**
     * Test the property 'fieldConfigurationId'
     */
    @Test
    public void fieldConfigurationIdTest() {
        // TODO: test fieldConfigurationId
    }

}
