/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.coscene.jira.client.v2.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for IssueTypeDetails
 */
public class IssueTypeDetailsTest {
    private final IssueTypeDetails model = new IssueTypeDetails();

    /**
     * Model tests for IssueTypeDetails
     */
    @Test
    public void testIssueTypeDetails() {
        // TODO: test IssueTypeDetails
    }

    /**
     * Test the property 'self'
     */
    @Test
    public void selfTest() {
        // TODO: test self
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'iconUrl'
     */
    @Test
    public void iconUrlTest() {
        // TODO: test iconUrl
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'subtask'
     */
    @Test
    public void subtaskTest() {
        // TODO: test subtask
    }

    /**
     * Test the property 'avatarId'
     */
    @Test
    public void avatarIdTest() {
        // TODO: test avatarId
    }

    /**
     * Test the property 'entityId'
     */
    @Test
    public void entityIdTest() {
        // TODO: test entityId
    }

    /**
     * Test the property 'hierarchyLevel'
     */
    @Test
    public void hierarchyLevelTest() {
        // TODO: test hierarchyLevel
    }

    /**
     * Test the property 'scope'
     */
    @Test
    public void scopeTest() {
        // TODO: test scope
    }

}
