/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.coscene.jira.client.v2.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for ProjectIssueTypesHierarchyLevel
 */
public class ProjectIssueTypesHierarchyLevelTest {
    private final ProjectIssueTypesHierarchyLevel model = new ProjectIssueTypesHierarchyLevel();

    /**
     * Model tests for ProjectIssueTypesHierarchyLevel
     */
    @Test
    public void testProjectIssueTypesHierarchyLevel() {
        // TODO: test ProjectIssueTypesHierarchyLevel
    }

    /**
     * Test the property 'entityId'
     */
    @Test
    public void entityIdTest() {
        // TODO: test entityId
    }

    /**
     * Test the property 'level'
     */
    @Test
    public void levelTest() {
        // TODO: test level
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'issueTypes'
     */
    @Test
    public void issueTypesTest() {
        // TODO: test issueTypes
    }

}
