/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.coscene.jira.client.v2.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for UpdateUserToGroupBean
 */
public class UpdateUserToGroupBeanTest {
    private final UpdateUserToGroupBean model = new UpdateUserToGroupBean();

    /**
     * Model tests for UpdateUserToGroupBean
     */
    @Test
    public void testUpdateUserToGroupBean() {
        // TODO: test UpdateUserToGroupBean
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    public void accountIdTest() {
        // TODO: test accountId
    }

}
