/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.coscene.jira.client.v3.api;

import io.coscene.jira.client.v3.ApiException;
import io.coscene.jira.client.v3.model.NotificationScheme;
import io.coscene.jira.client.v3.model.PageBeanNotificationScheme;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * API tests for IssueNotificationSchemesApi
 */
@Disabled
public class IssueNotificationSchemesApiTest {

    private final IssueNotificationSchemesApi api = new IssueNotificationSchemesApi();

    /**
     * Get notification scheme
     *
     * Returns a [notification scheme](https://confluence.atlassian.com/x/8YdKLg), including the list of events and the recipients who will receive notifications for those events.  **[Permissions](#permissions) required:** Permission to access Jira, however the user must have permission to administer at least one project associated with the notification scheme.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getNotificationSchemeTest() throws ApiException {
        Long id = null;
        String expand = null;
        NotificationScheme response = api.getNotificationScheme(id, expand);
        // TODO: test validations
    }

    /**
     * Get notification schemes paginated
     *
     * Returns a [paginated](#pagination) list of [notification schemes](https://confluence.atlassian.com/x/8YdKLg) ordered by display name.  *Note that you should allow for events without recipients to appear in responses.*  **[Permissions](#permissions) required:** Permission to access Jira, however the user must have permission to administer at least one project associated with a notification scheme for it to be returned.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getNotificationSchemesTest() throws ApiException {
        Long startAt = null;
        Integer maxResults = null;
        String expand = null;
        PageBeanNotificationScheme response = api.getNotificationSchemes(startAt, maxResults, expand);
        // TODO: test validations
    }

}
